// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv_aYDo8Nd5PDDDBzpQZbTpWT1Dmzz2LU',
    appId: '1:769695195333:web:46c0a35aebccc57958d0ac',
    messagingSenderId: '769695195333',
    projectId: 'devcolorguide',
    authDomain: 'devcolorguide.firebaseapp.com',
    storageBucket: 'devcolorguide.appspot.com',
    measurementId: 'G-NHV7ZRMV77',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuxyNXk85SBts70Z_-bybMrR6LA-vP7Eo',
    appId: '1:769695195333:ios:16dcfed4b59d8b8d58d0ac',
    messagingSenderId: '769695195333',
    projectId: 'devcolorguide',
    storageBucket: 'devcolorguide.appspot.com',
    iosClientId: '769695195333-mteuc39b8hbvl185ginofst42i69h9gp.apps.googleusercontent.com',
    iosBundleId: 'dev.askabhishekthakur.devcolorguide',
  );
}
